### ISSUE TITLE
Cannot run RunNewMolecules.py

### ISSUE THREAD

**Issue by ruslankotl** [emmaking-smith/SET_LSF_CODE#1]
Hello,

I was testing the model inference module on a sample dataset provided and I found it refers to a model outside the repository. (RunNewMolecules.py, line 73)
`train_path = '/gpfs/workspace/users/kingse01/model_inputs/mpnn/old_gss_train_metallo.pickle'`
Could you please include this model with the repository?

**Comment by emmaking-smith** [comment]
It should work now.

**Comment by emmaking-smith** [comment]
> Hello,
> 
> I was testing the model inference module on a sample dataset provided and I found it refers to a model outside the repository. (RunNewMolecules.py, line 73) `train_path = '/gpfs/workspace/users/kingse01/model_inputs/mpnn/old_gss_train_metallo.pickle'` Could you please include this model with the repository?

It should work now.
